services:
  api-gateway:
    container_name: api-gateway
    image: tyla42e/api-gateway:latest
    pull_policy: if_not_present
    environment:
      - AUTH_SERVICE_URL=http://auth-service:4005
    networks:
      - internal
    ports:
      - 4004:4004

networks:
  internal:
    external: true
