services:
  analytics-service:
    container_name: analytics-service
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    image: tyla42e/analytics-service:latest
    networks:
      - internal
    ports:
      - 4002:4002

networks:
  internal:
    external: true
 