services:
  service-registry:
    container_name: service-registry

    image: tyla42e/service-registry:latest
    pull_policy: if_not_present
    networks:
      - internal
    ports:
      - 8761:8761
networks:
  internal:
    external: true
