server:
  port: 4004

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            
        - id: PATIENT-SERVICE-ROUTE
          uri: lb://PATIENT-SERVICE
          predicates:
            - Path=/api/v1/patients/**
          filters: 
            - StripPrefix=1
            - JwtValidation
            

        - id: api-docs-patient-route
          uri: lb://PATIENT-SERVICE
          predicates:
            - Path=/swagger-ui
          filters:
            - StripPrefix=1
        
          
