services:
  patient-service:
    depends_on:
      - patient_service_db
    container_name: patient-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient_service_db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DLL_AUTO: update
      SPRING_SQL_INIT_MODE: always 
      BILLING_SERVICE_ADDRESS: billing-service
      BILLING_SERVICE_GRPC_PORT: 9001
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    image: tyla42e/patient-service:latest
    pull_policy: if_not_present
    ports:
      - 4000:4000
    networks:
      - internal
  
  patient_service_db:
    container_name: patient_service_db
    environment:
      POSTGRES_DB: db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin_user
    image: postgres:latest
    pull_policy: if_not_present
    networks:
      - internal
    ports:
      - 5002:5432
    volumes:
      - type: bind
        source: pgdata
        target: /var/lib/postgresql/data
        bind: 
          create_host_path: true
networks:
  internal:
    external: true
