services:
  billing-service:
    container_name: billing-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient_service_db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DLL_AUTO: update
      SPRING_SQL_INIT_MODE: always 
    image: tyla42e/billing-service:latest
    networks:
      - internal
    ports:
      - 4001:4001
      - 9001:9001

networks:
  internal:
    driver: bridge
